interface ZIF_I_ROLEGENERATION_C
  public .


  interfaces /BOBF/IF_LIB_CONSTANTS .

  constants:
    BEGIN OF SC_ACTION,
      BEGIN OF ZI_ROLEGENERATION,
 CREATE_ZI_ROLEGENERATION       TYPE /BOBF/ACT_KEY VALUE '0E7343095AA91EEBA2E131FD7A3EEEE7',
 DELETE_ZI_ROLEGENERATION       TYPE /BOBF/ACT_KEY VALUE '0E7343095AA91EEBA2E131FD7A3F6EE7',
 LOCK_ZI_ROLEGENERATION         TYPE /BOBF/ACT_KEY VALUE '0E7343095AA91EEBA2E131FD7A3E2EE7',
 SAVE_ZI_ROLEGENERATION         TYPE /BOBF/ACT_KEY VALUE '0E7343095AA91EEBA2E131FD7A3FEEE7',
 UNLOCK_ZI_ROLEGENERATION       TYPE /BOBF/ACT_KEY VALUE '0E7343095AA91EEBA2E131FD7A3E6EE7',
 UPDATE_ZI_ROLEGENERATION       TYPE /BOBF/ACT_KEY VALUE '0E7343095AA91EEBA2E131FD7A3F2EE7',
 VALIDATE_ZI_ROLEGENERATION     TYPE /BOBF/ACT_KEY VALUE '0E7343095AA91EEBA2E131FD7A3FAEE7',
      END OF ZI_ROLEGENERATION,
    END OF SC_ACTION .
  constants:
    BEGIN OF SC_ACTION_ATTRIBUTE,
        BEGIN OF ZI_ROLEGENERATION,
        BEGIN OF LOCK_ZI_ROLEGENERATION,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
 LEGACY_DAC_KEY                 TYPE STRING VALUE 'LEGACY_DAC_KEY',
        END OF LOCK_ZI_ROLEGENERATION,
        BEGIN OF UNLOCK_ZI_ROLEGENERATION,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
 LEGACY_DAC_KEY                 TYPE STRING VALUE 'LEGACY_DAC_KEY',
        END OF UNLOCK_ZI_ROLEGENERATION,
      END OF ZI_ROLEGENERATION,
    END OF SC_ACTION_ATTRIBUTE .
  constants:
    BEGIN OF SC_ALTERNATIVE_KEY,
      BEGIN OF ZI_ROLEGENERATION,
 DB_KEY                         TYPE /BOBF/OBM_ALTKEY_KEY VALUE '0E7343095AA91EEBA2E132285C970EE7',
      END OF ZI_ROLEGENERATION,
    END OF SC_ALTERNATIVE_KEY .
  constants:
    BEGIN OF SC_ASSOCIATION,
      BEGIN OF ZI_ROLEGENERATION,
 LOCK                           TYPE /BOBF/OBM_ASSOC_KEY VALUE '0E7343095AA91EEBA2E131FD7A3E0EE7',
 MESSAGE                        TYPE /BOBF/OBM_ASSOC_KEY VALUE '0E7343095AA91EEBA2E131FD7A3DCEE7',
 PROPERTY                       TYPE /BOBF/OBM_ASSOC_KEY VALUE '0E7343095AA91EEBA2E131FD7A3ECEE7',
      END OF ZI_ROLEGENERATION,
      BEGIN OF ZI_ROLEGENERATION_LOCK,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '0E7343095AA91EEBA2E131FD7A404EE7',
      END OF ZI_ROLEGENERATION_LOCK,
      BEGIN OF ZI_ROLEGENERATION_MESSAGE,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '0E7343095AA91EEBA2E131FD7A402EE7',
      END OF ZI_ROLEGENERATION_MESSAGE,
      BEGIN OF ZI_ROLEGENERATION_PROPERTY,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '0E7343095AA91EEBA2E131FD7A406EE7',
      END OF ZI_ROLEGENERATION_PROPERTY,
    END OF SC_ASSOCIATION .
  constants:
    BEGIN OF SC_ASSOCIATION_ATTRIBUTE,
      BEGIN OF ZI_ROLEGENERATION,
        BEGIN OF PROPERTY,
 ALL_NODE_PROPERTY              TYPE STRING VALUE 'ALL_NODE_PROPERTY',
 ALL_NODE_ATTRIBUTE_PROPERTY    TYPE STRING VALUE 'ALL_NODE_ATTRIBUTE_PROPERTY',
 ALL_ASSOCIATION_PROPERTY       TYPE STRING VALUE 'ALL_ASSOCIATION_PROPERTY',
 ALL_ASSOCIATION_ATTRIBUTE_PROP TYPE STRING VALUE 'ALL_ASSOCIATION_ATTRIBUTE_PROP',
 ALL_ACTION_PROPERTY            TYPE STRING VALUE 'ALL_ACTION_PROPERTY',
 ALL_ACTION_ATTRIBUTE_PROPERTY  TYPE STRING VALUE 'ALL_ACTION_ATTRIBUTE_PROPERTY',
 ALL_QUERY_PROPERTY             TYPE STRING VALUE 'ALL_QUERY_PROPERTY',
 ALL_QUERY_ATTRIBUTE_PROPERTY   TYPE STRING VALUE 'ALL_QUERY_ATTRIBUTE_PROPERTY',
 ALL_SUBTREE_PROPERTY           TYPE STRING VALUE 'ALL_SUBTREE_PROPERTY',
        END OF PROPERTY,
      END OF ZI_ROLEGENERATION,
    END OF SC_ASSOCIATION_ATTRIBUTE .
  constants:
    SC_BO_KEY  TYPE /BOBF/OBM_BO_KEY VALUE '0E7343095AA91EEBA2E131E0EE344EE7' .
  constants:
    SC_BO_NAME TYPE /BOBF/OBM_NAME VALUE 'ZI_ROLEGENERATION' .
  constants:
    BEGIN OF SC_DETERMINATION,
      BEGIN OF ZI_ROLEGENERATION,
 ACTION_AND_FIELD_CONTROL       TYPE /BOBF/DET_KEY VALUE '0E7343095AA91EEBA2E132285C972EE7',
      END OF ZI_ROLEGENERATION,
    END OF SC_DETERMINATION .
  constants:
    SC_MODEL_VERSION TYPE /BOBF/CONF_VERSION VALUE '00000' .
  constants:
    BEGIN OF SC_NODE,
 ZI_ROLEGENERATION              TYPE /BOBF/OBM_NODE_KEY VALUE '0E7343095AA91EEBA2E131FD7A3D6EE7',
 ZI_ROLEGENERATION_LOCK         TYPE /BOBF/OBM_NODE_KEY VALUE '0E7343095AA91EEBA2E131FD7A3DEEE7',
 ZI_ROLEGENERATION_MESSAGE      TYPE /BOBF/OBM_NODE_KEY VALUE '0E7343095AA91EEBA2E131FD7A3DAEE7',
 ZI_ROLEGENERATION_PROPERTY     TYPE /BOBF/OBM_NODE_KEY VALUE '0E7343095AA91EEBA2E131FD7A3EAEE7',
    END OF SC_NODE .
  constants:
    BEGIN OF SC_NODE_ATTRIBUTE,
      BEGIN OF ZI_ROLEGENERATION,
  NODE_DATA                      TYPE STRING VALUE 'NODE_DATA',
  DOCBLOCK                       TYPE STRING VALUE 'DOCBLOCK',
  ROLETYPE                       TYPE STRING VALUE 'ROLETYPE',
      END OF ZI_ROLEGENERATION,
    END OF SC_NODE_ATTRIBUTE .
  constants:
    BEGIN OF SC_NODE_CATEGORY,
      BEGIN OF ZI_ROLEGENERATION,
 ROOT                           TYPE /BOBF/OBM_NODE_CAT_KEY VALUE '0E7343095AA91EEBA2E131FD7A3D8EE7',
      END OF ZI_ROLEGENERATION,
    END OF SC_NODE_CATEGORY .
endinterface.
